// Generated file. Do not edit manually.

class QuranRadioItem {
  final String id;
  final String name; // Arabic Name
  final String englishName; // English Name
  final String url;
  final String category; // 'quran', 'tafsir', 'adhkar', 'ruqyah', 'varied'

  const QuranRadioItem({
    required this.id,
    required this.name,
    required this.englishName,
    required this.url,
    required this.category,
  });
}

class QuranRadioService {
  static const List<QuranRadioItem> stations = [
    QuranRadioItem(
      id: '1',
      name: 'إذاعة إبراهيم الأخضر',
      englishName: 'Radio Ibrahim Al-Akdar',
      url: 'https://backup.qurango.net/radio/ibrahim_alakdar',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '2',
      name: 'إذاعة شيخ أبو بكر الشاطري',
      englishName: 'Radio Shaik Abu Bakr Al Shatri',
      url: 'https://backup.qurango.net/radio/shaik_abu_bakr_al_shatri',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '3',
      name: 'إذاعة أحمد العجمي',
      englishName: 'Radio Ahmad Al-Ajmy',
      url: 'https://backup.qurango.net/radio/ahmad_alajmy',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '4',
      name: 'إذاعة أحمد الحواشي',
      englishName: 'Radio Ahmad Al-Hawashi',
      url: 'https://backup.qurango.net/radio/ahmad_alhawashi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '5',
      name: 'إذاعة أحمد صابر',
      englishName: 'Radio Ahmad Saber',
      url: 'https://backup.qurango.net/radio/ahmad_saber',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '6',
      name: 'إذاعة أحمد نعينع',
      englishName: 'Radio Ahmad Nauina',
      url: 'https://backup.qurango.net/radio/ahmad_nauina',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '7',
      name: 'إذاعة أكرم العلاقمي',
      englishName: 'Radio Akram Alalaqmi',
      url: 'https://backup.qurango.net/radio/akram_alalaqmi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '8',
      name: 'إذاعة إدريس أبكر',
      englishName: 'Radio Idrees Abkr',
      url: 'https://backup.qurango.net/radio/idrees_abkr',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '9',
      name: 'إذاعة الزين محمد أحمد',
      englishName: 'Radio Alzain Mohammad Ahmad',
      url: 'https://backup.qurango.net/radio/alzain_mohammad_ahmad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '10',
      name: 'إذاعة القارئ ياسين',
      englishName: 'Radio Al-Qaria Yassen',
      url: 'https://backup.qurango.net/radio/alqaria_yassen',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '11',
      name: 'إذاعة العيون الكوشي',
      englishName: 'Radio Aloyoon Al-Koshi',
      url: 'https://backup.qurango.net/radio/aloyoon_alkoshi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '12',
      name: 'إذاعة توفيق الصايغ',
      englishName: 'Radio Tawfeeq As-Sayegh',
      url: 'https://backup.qurango.net/radio/tawfeeq_assayegh',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '13',
      name: 'إذاعة جمال شاكر عبدالله',
      englishName: 'Radio Jamal Shaker Abdullah',
      url: 'https://backup.qurango.net/radio/jamal_shaker_abdullah',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '14',
      name: 'إذاعة خالد القحطاني',
      englishName: 'Radio Khaled Al-Qahtani',
      url: 'https://backup.qurango.net/radio/khaled_alqahtani',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '15',
      name: 'إذاعة خالد عبدالكافي',
      englishName: 'Radio Khalid Abdulkafi',
      url: 'https://backup.qurango.net/radio/khalid_abdulkafi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '16',
      name: 'إذاعة خليفة الطنيجي',
      englishName: 'Radio Khalifa Altunaiji',
      url: 'https://backup.qurango.net/radio/khalifa_altunaiji',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '17',
      name: 'إذاعة سعد الغامدي',
      englishName: 'Radio Saad Al-Ghamdi',
      url: 'https://backup.qurango.net/radio/saad_alghamdi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '18',
      name: 'إذاعة سعود الشريم',
      englishName: 'Radio Saud Al-Shuraim',
      url: 'https://backup.qurango.net/radio/saud_alshuraim',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '19',
      name: 'إذاعة سهل ياسين',
      englishName: 'Radio Sahl Yassin',
      url: 'https://backup.qurango.net/radio/sahl_yassin',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '20',
      name: 'إذاعة زكي داغستاني',
      englishName: 'Radio Zaki Daghistani',
      url: 'https://backup.qurango.net/radio/zaki_daghistani',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '21',
      name: 'إذاعة سيد رمضان',
      englishName: 'Radio Sayeed Ramadan',
      url: 'https://backup.qurango.net/radio/sayeed_ramadan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '22',
      name: 'إذاعة شيرزاد عبدالرحمن طاهر',
      englishName: 'Radio Shirazad Taher',
      url: 'https://backup.qurango.net/radio/shirazad_taher',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '23',
      name: 'إذاعة صابر عبدالحكم',
      englishName: 'Radio Saber Abdulhakm',
      url: 'https://backup.qurango.net/radio/saber_abdulhakm',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '24',
      name: 'إذاعة صلاح البدير',
      englishName: 'Radio Salah Albudair',
      url: 'https://backup.qurango.net/radio/salah_albudair',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '25',
      name: 'إذاعة صلاح الهاشم',
      englishName: 'Radio Salah Alhashim',
      url: 'https://backup.qurango.net/radio/salah_alhashim',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '26',
      name: 'إذاعة صلاح بو خاطر',
      englishName: 'Radio Slaah Bukhatir',
      url: 'https://backup.qurango.net/radio/slaah_bukhatir',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '27',
      name: 'إذاعة عادل ريان',
      englishName: 'Radio Adel Ryyan',
      url: 'https://backup.qurango.net/radio/adel_ryyan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '28',
      name: 'إذاعة عبدالبارئ الثبيتي',
      englishName: 'Radio Abdelbari Al-Thoubayti',
      url: 'https://backup.qurango.net/radio/abdelbari_altoubayti',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '29',
      name: 'إذاعة عبدالبارئ محمد',
      englishName: 'Radio Abdulbari Mohammad',
      url: 'https://backup.qurango.net/radio/abdulbari_mohammad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '30',
      name: 'إذاعة عبدالباسط عبدالصمد',
      englishName: 'Radio Abdulbasit Abdulsamad',
      url: 'https://backup.qurango.net/radio/abdulbasit_abdulsamad_mojawwad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '31',
      name: 'إذاعة عبدالباسط عبدالصمد',
      englishName: 'Radio Abdulbasit Abdulsamad',
      url: 'https://backup.qurango.net/radio/abdulbasit_abdulsamad_warsh',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '32',
      name: 'إذاعة عبدالباسط عبدالصمد',
      englishName: 'Radio Abdulbasit Abdulsamad',
      url: 'https://backup.qurango.net/radio/abdulbasit_abdulsamad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '33',
      name: 'إذاعة عبدالرحمن السديس',
      englishName: 'Radio Abdulrahman Alsudaes',
      url: 'https://backup.qurango.net/radio/abdulrahman_alsudaes',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '34',
      name: 'إذاعة عبدالعزيز الأحمد',
      englishName: 'Radio Abdul Aziz Al-Ahmad',
      url: 'https://backup.qurango.net/radio/abdul_aziz_alahmad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '35',
      name: 'إذاعة عبدالله المطرود',
      englishName: 'Radio Abdullah Al-Mattrod',
      url: 'https://backup.qurango.net/radio/abdullah_almattrod',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '36',
      name: 'إذاعة عبدالله بصفر',
      englishName: 'Radio Abdullah Basfer',
      url: 'https://backup.qurango.net/radio/abdullah_basfer',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '37',
      name: 'إذاعة عبدالله خياط',
      englishName: 'Radio Abdullah Khayyat',
      url: 'https://backup.qurango.net/radio/abdullah_khayyat',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '38',
      name: 'إذاعة عبدالله عواد الجهني',
      englishName: 'Radio Abdullah Al-Johany',
      url: 'https://backup.qurango.net/radio/abdullah_aljohany',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '39',
      name: 'إذاعة عبدالرشيد صوفي',
      englishName: 'Radio Abdulrasheed Soufi',
      url: 'https://backup.qurango.net/radio/abdulrasheed_soufi_khalaf',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '40',
      name: 'إذاعة عبدالرشيد صوفي',
      englishName: 'Radio Abdulrasheed Soufi',
      url: 'https://backup.qurango.net/radio/abdulrasheed_soufi_assosi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '41',
      name: 'إذاعة عبدالمحسن الحارثي',
      englishName: 'Radio Abdulmohsin Al-Harthy',
      url: 'https://backup.qurango.net/radio/abdulmohsin_alharthy',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '42',
      name: 'إذاعة عبدالمحسن القاسم',
      englishName: 'Radio Abdulmohsen Al-Qasim',
      url: 'https://backup.qurango.net/radio/abdulmohsen_alqasim',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '43',
      name: 'إذاعة عبدالمحسن العبيكان',
      englishName: 'Radio Abdulmohsin Al-Obaikan',
      url: 'https://backup.qurango.net/radio/abdulmohsin_alobaikan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '44',
      name: 'إذاعة عبدالهادي أحمد كناكري',
      englishName: 'Radio Abdulhadi Kanakeri',
      url: 'https://backup.qurango.net/radio/abdulhadi_kanakeri',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '45',
      name: 'إذاعة عبدالودود حنيف',
      englishName: 'Radio Abdulwadood Haneef',
      url: 'https://backup.qurango.net/radio/abdulwadood_haneef',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '46',
      name: 'إذاعة علي بن عبدالرحمن الحذيفي',
      englishName: 'Radio Ali Alhuthaifi',
      url: 'https://backup.qurango.net/radio/ali_alhuthaifi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '47',
      name: 'إذاعة علي الحذيفي',
      englishName: 'Radio Ali Alhuthaifi',
      url: 'https://backup.qurango.net/radio/ali_alhuthaifi_qalon',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '48',
      name: 'إذاعة علي جابر',
      englishName: 'Radio Ali Jaber',
      url: 'https://backup.qurango.net/radio/ali_jaber',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '49',
      name: 'إذاعة علي حجاج السويسي',
      englishName: 'Radio Ali Hajjaj Alsouasi',
      url: 'https://backup.qurango.net/radio/ali_hajjaj_alsouasi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '50',
      name: 'إذاعة عماد زهير حافظ',
      englishName: 'Radio Emad Hafez',
      url: 'https://backup.qurango.net/radio/emad_hafez',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '51',
      name: 'إذاعة عمر القزابري',
      englishName: 'Radio Omar Al-Qazabri',
      url: 'https://backup.qurango.net/radio/omar_alqazabri',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '52',
      name: 'إذاعة فارس عباد',
      englishName: 'Radio Fares Abbad',
      url: 'https://backup.qurango.net/radio/fares_abbad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '53',
      name: 'إذاعة ناصر القطامي',
      englishName: 'Radio Nasser Alqatami',
      url: 'https://backup.qurango.net/radio/nasser_alqatami',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '54',
      name: 'إذاعة نبيل الرفاعي',
      englishName: 'Radio Nabil Al Rifay',
      url: 'https://backup.qurango.net/radio/nabil_al_rifay',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '55',
      name: 'إذاعة نعمة الحسان',
      englishName: 'Radio Neamah Al-Hassan',
      url: 'https://backup.qurango.net/radio/neamah_alhassan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '56',
      name: 'إذاعة هاني الرفاعي',
      englishName: 'Radio Hani Arrifai',
      url: 'https://backup.qurango.net/radio/hani_arrifai',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '57',
      name: 'إذاعة وليد النائحي',
      englishName: 'Radio Waleed Alnaehi',
      url: 'https://backup.qurango.net/radio/waleed_alnaehi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '58',
      name: 'إذاعة ياسر الدوسري',
      englishName: 'Radio Yasser Al-Dosari',
      url: 'https://backup.qurango.net/radio/yasser_aldosari',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '59',
      name: 'إذاعة ياسر القرشي',
      englishName: 'Radio Yasser Al-Qurashi',
      url: 'https://backup.qurango.net/radio/yasser_alqurashi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '60',
      name: 'إذاعة ياسر المزروعي',
      englishName: 'Radio Yasser Al-Mazroyee',
      url: 'https://backup.qurango.net/radio/yasser_almazroyee',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '61',
      name: 'إذاعة يحيى حوا',
      englishName: 'Radio Yahya Hawwa',
      url: 'https://backup.qurango.net/radio/yahya_hawwa',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '62',
      name: 'إذاعة يوسف الشويعي',
      englishName: 'Radio Yousef Alshoaey',
      url: 'https://backup.qurango.net/radio/yousef_alshoaey',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '63',
      name: 'إذاعة ماهر المعيقلي',
      englishName: 'Radio Maher Al Meaqli',
      url: 'https://backup.qurango.net/radio/maher',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '64',
      name: 'إذاعة محمد الطبلاوي',
      englishName: 'Radio Mohammad Al-Tablaway',
      url: 'https://backup.qurango.net/radio/mohammad_altablaway',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '65',
      name: 'إذاعة محمد اللحيدان',
      englishName: 'Radio Mohammed Al-Lohaidan',
      url: 'https://backup.qurango.net/radio/mohammed_allohaidan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '66',
      name: 'إذاعة محمد أيوب',
      englishName: 'Radio Mohammed Ayyub',
      url: 'https://backup.qurango.net/radio/mohammed_ayyub',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '67',
      name: 'إذاعة محمد صالح عالم شاه',
      englishName: 'Radio Mohammad Saleh Alim Shah',
      url: 'https://backup.qurango.net/radio/mohammad_saleh_alim_shah',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '68',
      name: 'إذاعة محمد جبريل',
      englishName: 'Radio Mohammed Jibreel',
      url: 'https://backup.qurango.net/radio/mohammed_jibreel',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '69',
      name: 'إذاعة محمد صديق المنشاوي',
      englishName: 'Radio Mohammed Siddiq Al-Minshawi',
      url: 'https://backup.qurango.net/radio/mohammed_siddiq_alminshawi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '70',
      name: 'إذاعة محمد صديق المنشاوي',
      englishName: 'Radio Mohammed Siddiq Al-Minshawi',
      url: 'https://backup.qurango.net/radio/mohammed_siddiq_alminshawi_mojawwad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '71',
      name: 'إذاعة محمد عبدالكريم',
      englishName: 'Radio Mohammad Abdullkarem',
      url: 'https://backup.qurango.net/radio/mohammad_abdullkarem',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '72',
      name: 'إذاعة محمد عبدالحكيم سعيد العبدالله',
      englishName: 'Radio Mohammad Al-Abdullah',
      url: 'https://backup.qurango.net/radio/mohammad_alabdullah_albizi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '73',
      name: 'إذاعة محمد عبدالحكيم سعيد العبدالله',
      englishName: 'Radio Mohammad Al-Abdullah',
      url: 'https://backup.qurango.net/radio/mohammad_alabdullah_aldorai',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '74',
      name: 'إذاعة محمود خليل الحصري',
      englishName: 'Radio Mahmoud Khalil Al-Hussary',
      url: 'https://backup.qurango.net/radio/mahmoud_khalil_alhussary',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '75',
      name: 'إذاعة محمود خليل الحصري',
      englishName: 'Radio Mahmoud Khalil Al-Hussary',
      url: 'https://backup.qurango.net/radio/mahmoud_khalil_alhussary_mojawwad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '76',
      name: 'إذاعة محمود خليل الحصري',
      englishName: 'Radio Mahmoud Khalil Al-Hussary',
      url: 'https://backup.qurango.net/radio/mahmoud_khalil_alhussary_warsh',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '77',
      name: 'إذاعة محمود علي البنا',
      englishName: 'Radio Mahmoud Ali  Albanna',
      url: 'https://backup.qurango.net/radio/mahmoud_ali__albanna',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '78',
      name: 'إذاعة محمود علي البنا',
      englishName: 'Radio Mahmoud Ali  Albanna',
      url: 'https://backup.qurango.net/radio/mahmoud_ali__albanna_mojawwad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '79',
      name: 'إذاعة مشاري العفاسي',
      englishName: 'Radio Mishary Alafasi',
      url: 'https://backup.qurango.net/radio/mishary_alafasi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '80',
      name: 'إذاعة مصطفى إسماعيل',
      englishName: 'Radio Mustafa Ismail',
      url: 'https://backup.qurango.net/radio/mustafa_ismail',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '81',
      name: 'إذاعة مصطفى اللاهوني',
      englishName: 'Radio Mustafa Al-Lahoni',
      url: 'https://backup.qurango.net/radio/mustafa_allahoni',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '82',
      name: 'إذاعة مصطفى رعد العزاوي',
      englishName: 'Radio Mustafa raad Alazawy',
      url: 'https://backup.qurango.net/radio/mustafa_raad_alazawy',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '83',
      name: 'إذاعة مفتاح السلطني',
      englishName: 'Radio Muftah Alsaltany',
      url: 'https://backup.qurango.net/radio/muftah_alsaltany_aldori_an_abi_amr ',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '84',
      name: 'إذاعة ماهر شخاشيرو',
      englishName: 'Radio Maher Shakhashero',
      url: 'https://backup.qurango.net/radio/maher_shakhashero',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '85',
      name: 'إذاعة محمود الشيمي',
      englishName: 'Radio Mahmood AlSheimy',
      url: 'https://backup.qurango.net/radio/mahmood_alsheimy',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '86',
      name: 'إذاعة خالد المهنا',
      englishName: 'Radio Khalid Almohana',
      url: 'https://backup.qurango.net/radio/khalid_almohana',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '87',
      name: 'إذاعة عادل الكلباني',
      englishName: 'Radio Adel Al-Khalbany',
      url: 'https://backup.qurango.net/radio/adel_alkhalbany',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '88',
      name: 'إذاعة موسى بلال',
      englishName: 'Radio Mousa Bilal',
      url: 'https://backup.qurango.net/radio/mousa_bilal',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '89',
      name: 'حاتم فريد الواعر',
      englishName: 'Radio Hatem Fareed Alwaer',
      url: 'https://backup.qurango.net/radio/hatem_fareed_alwaer',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '90',
      name: 'إذاعة محمود الرفاعي',
      englishName: 'Radio Mahmood Al rifai',
      url: 'https://backup.qurango.net/radio/mahmood_al_rifai',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '91',
      name: 'إذاعة ابراهيم الدوسري',
      englishName: 'Radio Ibrahim Aldosari',
      url: 'https://backup.qurango.net/radio/ibrahim_aldosari',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '92',
      name: 'إذاعة مفتاح السلطني',
      englishName: 'Radio Muftah Alsaltany',
      url: 'https://backup.qurango.net/radio/muftah_alsaltany_aldorai',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '93',
      name: 'إذاعة جمعان العصيمي',
      englishName: 'Radio Jamaan Alosaimi',
      url: 'https://backup.qurango.net/radio/jamaan_alosaimi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '94',
      name: 'إذاعة مفتاح السلطني',
      englishName: 'Radio Muftah Alsaltany',
      url: 'https://backup.qurango.net/radio/muftah_alsaltany',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '95',
      name: 'إذاعة يوسف بن نوح أحمد',
      englishName: 'Radio Yousef Bin Noah Ahmad',
      url: 'https://backup.qurango.net/radio/yousef_bin_noah_ahmad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '96',
      name: 'إذاعة مفتاح السلطني',
      englishName: 'Radio Muftah Alsaltany',
      url: 'https://backup.qurango.net/radio/muftah_alsaltany_ibn_thakwan_an_ibn_amr',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '97',
      name: 'إذاعة معيض الحارثي',
      englishName: 'Radio Moeedh Alharthi',
      url: 'https://backup.qurango.net/radio/moeedh_alharthi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '98',
      name: 'إذاعة محمد رشاد الشريف',
      englishName: 'Radio Mohammad Rashad Alshareef',
      url: 'https://backup.qurango.net/radio/mohammad_rashad_alshareef',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '99',
      name: 'إذاعة أحمد خضر الطرابلسي',
      englishName: 'Radio Ahmad Khader Al-Tarabulsi',
      url: 'https://backup.qurango.net/radio/ahmad_khader_altarabulsi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '100',
      name: 'إذاعة أحمد الطرابلسي',
      englishName: 'Radio Ahmed Al-trabulsi',
      url: 'https://backup.qurango.net/radio/ahmed_altrabulsi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '101',
      name: 'إذاعة عبدالله الكندري',
      englishName: 'Radio Abdullah Al-Kandari',
      url: 'https://backup.qurango.net/radio/abdullah_alkandari',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '102',
      name: 'إذاعة أحمد عامر',
      englishName: 'Radio Ahmed Amer',
      url: 'https://backup.qurango.net/radio/ahmed_amer',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '103',
      name: 'إذاعة محمد عثمان خان',
      englishName: 'Radio Mohammed Osman Khan',
      url: 'https://backup.qurango.net/radio/mohammed_osman_khan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '104',
      name: 'إذاعة الدوكالي محمد العالم',
      englishName: 'Radio Addokali Mohammad Alalim',
      url: 'https://backup.qurango.net/radio/addokali_mohammad_alalim',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '105',
      name: 'إذاعة محمد عبدالكريم',
      englishName: 'Radio Mohammad Abdullkarem',
      url: 'https://backup.qurango.net/radio/mohammad_abdullkarem_alasbahani',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '106',
      name: 'إذاعة الفاتح محمد الزبير',
      englishName: 'Radio Alfateh Alzubair',
      url: 'https://backup.qurango.net/radio/alfateh_alzubair',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '107',
      name: 'إذاعة طارق عبدالغني دعوب',
      englishName: 'Radio Tareq Abdulgani daawob',
      url: 'https://backup.qurango.net/radio/tareq_abdulgani_daawob',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '108',
      name: 'الإذاعة العامة - اذاعة متنوعة لمختلف القراء',
      englishName: 'Main Radio',
      url: 'https://backup.qurango.net/radio/mix',
      category: 'varied',
    ),
    QuranRadioItem(
      id: '109',
      name: 'إذاعة -تلاوات خاشعة',
      englishName: 'Beautiful Recitations',
      url: 'https://backup.qurango.net/radio/salma',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '110',
      name: 'إذاعة تكبيرات العيد',
      englishName: 'Eid Takbeer',
      url: 'https://backup.qurango.net/radio/eid',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '111',
      name: 'إذاعة عبدالرحمن الماجد',
      englishName: 'Radio Abdulrahman Al-Majed',
      url: 'https://backup.qurango.net/radio/abdulrahman_almajed',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '113',
      name: 'إذاعة الفتاوى العامة',
      englishName: 'General Fatwa Radio',
      url: 'https://backup.qurango.net/radio/fatwa',
      category: 'varied',
    ),
    QuranRadioItem(
      id: '114',
      name: 'إذاعة الرقية الشرعية',
      englishName: 'Sharia ruqyah',
      url: 'https://backup.qurango.net/radio/roqiah',
      category: 'ruqyah',
    ),
    QuranRadioItem(
      id: '115',
      name: 'إذاعة ---سورة البقرة - لعدد من القراء',
      englishName: 'Surah Al-Baqarah - Many Reciters',
      url: 'https://backup.qurango.net/radio/albaqarah',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '116',
      name: 'إذاعة --تفسير القران الكريم',
      englishName: 'Quran Tafseer',
      url: 'https://backup.qurango.net/radio/tafseer',
      category: 'tafsir',
    ),
    QuranRadioItem(
      id: '117',
      name: 'إذاعة خالد الجليل',
      englishName: 'Khalid Al-Jileel',
      url: 'https://backup.qurango.net/radio/khalid_aljileel',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '118',
      name: 'إذاعة ناصر الماجد',
      englishName: 'Nasser Almajed',
      url: 'https://backup.qurango.net/radio/nasser_almajed',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '119',
      name: 'إذاعة هيثم الجدعاني',
      englishName: 'Haitham Aljudaany',
      url: 'https://backup.qurango.net/radio/hitham_aljadani',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '120',
      name: 'إذاعة أحمد خليل شاهين',
      englishName: 'Ahmad Shaheen',
      url: 'https://backup.qurango.net/radio/ahmad_shaheen',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '121',
      name: 'إذاعة عبدالله الموسى',
      englishName: 'Abdullah Al-Mousa - Radio',
      url: 'https://backup.qurango.net/radio/abdullah_almousa',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '122',
      name: 'إذاعة عبدالله الخلف',
      englishName: 'Abdullah Al-Khalaf',
      url: 'https://backup.qurango.net/radio/abdullah_alkhalaf',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '123',
      name: 'تراتيل قصيرة متميزة',
      englishName: 'Amazing short Recitations',
      url: 'https://backup.qurango.net/radio/tarateel',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '139',
      name: 'إذاعة ماجد الزامل',
      englishName: 'Radio Majed Al-Zamil',
      url: 'https://backup.qurango.net/radio/majed_alzamel',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '217',
      name: 'إذاعة بندر بليلة',
      englishName: 'Radio Bandar Balilah',
      url: 'https://backup.qurango.net/radio/bandar_balilah',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '248',
      name: 'إذاعة ناصر العصفور',
      englishName: 'Radio Nasser Alosfor',
      url: 'https://backup.qurango.net/radio/nasser_alosfor',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '261',
      name: 'إذاعة محمد أيوب - قراءة مميزة',
      englishName: 'Radio Muhammad Ayoub - Distinctive reading',
      url: 'https://backup.qurango.net/radio/ayyoub2',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '265',
      name: 'إذاعة أحمد ديبان',
      englishName: 'Ahmad Deban',
      url: 'https://backup.qurango.net/radio/ahmad_deban',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '274',
      name: 'أذاعة محمد أبوسنينة',
      englishName: 'Radio Muhammad Abu Sneina',
      url: 'https://backup.qurango.net/radio/sneineh',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '275',
      name: 'إذاعة محمد الأمين قنيوة',
      englishName: 'Radio Mohammed Al-Amin Qeniwa',
      url: 'https://backup.qurango.net/radio/qeniwa',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '287',
      name: 'إذاعة عبدالرحمن الشحات',
      englishName: 'Radio Abdulrahman Alshahhat',
      url: 'https://backup.qurango.net/radio/a_alshahhat',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '307',
      name: 'عبدالعزيز سحيم',
      englishName: 'Abdulaziz Sheim',
      url: 'https://backup.qurango.net/radio/a_sheim',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '10902',
      name: 'آيات السكينة',
      englishName: 'Verses of serenity',
      url: 'https://backup.qurango.net/radio/sakeenah',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '10903',
      name: 'إذاعة صور من حياة الصحابة والتابعين رضوان الله عليهم',
      englishName: 'Stories from the lives of the SAHABAH and TABE\'EEN, may ALLAH be pleased with them',
      url: 'https://backup.qurango.net/radio/sahabah',
      category: 'varied',
    ),
    QuranRadioItem(
      id: '10904',
      name: 'المختصر في تفسير القرآن الكريم',
      englishName: 'A summary of the interpretation of the Holy Quran',
      url: 'https://backup.qurango.net/radio/mukhtasartafsir',
      category: 'tafsir',
    ),
    QuranRadioItem(
      id: '10906',
      name: 'أذكار الصباح',
      englishName: 'Words of remembrance for morning',
      url: 'https://backup.qurango.net/radio/athkar_sabah',
      category: 'adhkar',
    ),
    QuranRadioItem(
      id: '10907',
      name: 'أذكار المساء',
      englishName: 'Words of remembrance for evening',
      url: 'https://backup.qurango.net/radio/athkar_masa',
      category: 'adhkar',
    ),
    QuranRadioItem(
      id: '21114',
      name: 'في ظلال السيرة النبوية - 400 حلقة عن سيرة نبينا محمد صلى الله عليه وسلم',
      englishName: 'In the shadows of the Prophet’s PBUH biography',
      url: 'https://backup.qurango.net/radio/fi_zilal_alsiyra',
      category: 'varied',
    ),
    QuranRadioItem(
      id: '21115',
      name: 'المختصر في السيرة النبوية',
      englishName: 'The Abridged Biography of the Prophet',
      url: 'https://backup.qurango.net/radio/almukhtasar_fi_alsiyra',
      category: 'tafsir',
    ),
    QuranRadioItem(
      id: '21116',
      name: 'كتاب الاختيارات الفقهية في مسائل العبادات والمعاملات',
      englishName: 'The book of jurisprudential choices in matters of worship and transactions',
      url: 'https://backup.qurango.net/radio/alaikhtiarat_alfiqhayh_bin_baz',
      category: 'varied',
    ),
    QuranRadioItem(
      id: '21117',
      name: 'تفسير القران الكريم-الخلاصة من تفسير الطبري',
      englishName: 'Interpretation of the Holy Qur’an - Conclusion from Tafsir al-Tabari',
      url: 'https://backup.qurango.net/radio/tabri',
      category: 'tafsir',
    ),
    QuranRadioItem(
      id: '109038',
      name: 'صالح الهبدان',
      englishName: 'Saleh Al-Habdan',
      url: 'https://backup.qurango.net/radio/saleh_alhabdan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109039',
      name: 'ترجمة معاني القرآن باللغة الأوردية - عبدالباسط عبدالصمد',
      englishName: 'Quran translation into Urdu - Abdulbasit',
      url: 'https://backup.qurango.net/radio/translation_quran_urdu_basit',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109040',
      name: 'ترجمة معاني القرآن باللغة الأسبانية',
      englishName: 'Quran translation into Spanish',
      url: 'https://backup.qurango.net/radio/translation_quran_spanish_afs',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109041',
      name: 'ترجمة معاني القرآن باللغة الألبانية',
      englishName: 'Quran translation into Albanian',
      url: 'https://backup.qurango.net/radio/translation_quran_albanian',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109042',
      name: 'ترجمة معاني القرآن باللغة الألمانية',
      englishName: 'Quran translation into German',
      url: 'https://backup.qurango.net/radio/translation_quran_german',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109043',
      name: 'ترجمة معاني القرآن باللغة الأمازيغية',
      englishName: 'Quran translation into Amazigh',
      url: 'https://backup.qurango.net/radio/translation_quran_tamazight',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109044',
      name: 'ترجمة معاني القرآن باللغة الأوردية',
      englishName: 'Quran in Urdu - Al-Sharim and Al-Sadis',
      url: 'https://backup.qurango.net/radio/translation_quran_urdu_sds_shur',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109045',
      name: 'ترجمة معاني القرآن باللغة الأوردية',
      englishName: 'Quran in Urdu - Qari Muhammad Manshawi',
      url: 'https://backup.qurango.net/radio/translation_quran_urdu_minsh',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109046',
      name: 'ترجمة معاني القرآن باللغة الإنجليزية',
      englishName: 'Quran translation into English - AbdulBasit Abdul Samad',
      url: 'https://backup.qurango.net/radio/translation_quran_english_basit',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109047',
      name: 'ترجمة معاني القرآن باللغة الإنجليزية',
      englishName: 'Quran translation into English - Abdullah Basfar',
      url: 'https://backup.qurango.net/radio/translation_quran_english_bsfr',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109048',
      name: 'ترجمة معاني القرآن باللغة الإنجليزية -ترجمة والك',
      englishName: 'Quran translation into English - translated by Walk',
      url: 'https://backup.qurango.net/radio/translation_quran_english_walk_basit',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109049',
      name: 'ترجمة معاني القرآن باللغة البرتغالية',
      englishName: 'Quran translation into Portuguese',
      url: 'https://backup.qurango.net/radio/translation_quran_portuguese',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109050',
      name: 'ترجمة معاني القرآن باللغة البوسنية',
      englishName: 'Quran translation into Bosnian',
      url: 'https://backup.qurango.net/radio/translation_quran_bosnia',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109051',
      name: 'ترجمة معاني القرآن باللغة التركية',
      englishName: 'Quran translation into Turkish',
      url: 'https://backup.qurango.net/radio/translation_quran_turkish',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109052',
      name: 'ترجمة معاني القرآن باللغة الروسية',
      englishName: 'Quran translation into Russian',
      url: 'https://backup.qurango.net/radio/translation_quran_Russia',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109053',
      name: 'ترجمة معاني القرآن باللغة الصينية',
      englishName: 'Quran translation into Chinese',
      url: 'https://backup.qurango.net/radio/translation_quran_chinese',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109054',
      name: 'ترجمة معاني القرآن باللغة الفارسية',
      englishName: 'Quran translation into Persian',
      url: 'https://backup.qurango.net/radio/translation_quran_farsi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109055',
      name: 'ترجمة معاني القرآن باللغة الفرنسية',
      englishName: 'Quran translation into French',
      url: 'https://backup.qurango.net/radio/translation_quran_french',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109056',
      name: 'ترجمة معاني القرآن باللغة الكردية',
      englishName: 'Quran translation into Kurdish',
      url: 'https://backup.qurango.net/radio/translation_quran_kurdish',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109057',
      name: 'ترجمة معاني القرآن باللغة الكورية',
      englishName: 'Quran translation into Korean',
      url: 'https://backup.qurango.net/radio/translation_quran_Korean',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109058',
      name: 'ترجمة معاني القرآن باللغة المجرية',
      englishName: 'Quran translation into Hungarian',
      url: 'https://backup.qurango.net/radio/translation_quran_hungarian',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109059',
      name: 'ترجمة معاني القرآن باللغة اليونانية',
      englishName: 'Quran translation into Greek',
      url: 'https://backup.qurango.net/radio/translation_quran_greek',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109060',
      name: 'سورة الملك',
      englishName: 'Al-Mulk Surah',
      url: 'https://backup.qurango.net/radio/Surah_Al-Mulk',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109061',
      name: 'فضل شهر رمضان',
      englishName: 'The virtue of the month of Ramadan',
      url: 'https://backup.qurango.net/radio/ramadan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109062',
      name: 'ترجمة معاني القرآن باللغة الهوسا',
      englishName: 'Translation of the meanings of the Quran in Hausa',
      url: 'https://backup.qurango.net/radio/Translation_Quran_Hausa',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109066',
      name: 'صحيح مسلم',
      englishName: 'Sahih Muslim',
      url: 'https://backup.qurango.net/radio/saheh-muslim',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109067',
      name: 'صحيح البخاري',
      englishName: 'Sahih al-Bukhari',
      url: 'https://backup.qurango.net/radio/saheh-bokharee',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109069',
      name: '***قصص الأنبياء***',
      englishName: 'Stories of the Prophets',
      url: 'https://backup.qurango.net/radio/alanbiya',
      category: 'varied',
    ),
    QuranRadioItem(
      id: '109073',
      name: 'رياض الصالحين',
      englishName: 'رياض الصالحين',
      url: 'https://backup.qurango.net/radio/riyad',
      category: 'varied',
    ),
    QuranRadioItem(
      id: '109074',
      name: 'عبدالله البعيجان',
      englishName: 'Abdullah Albuajan',
      url: 'https://backup.qurango.net/radio/buajan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109075',
      name: 'أحمد طالب بن حميد',
      englishName: 'Ahmad Talib bin Humaid',
      url: 'https://backup.qurango.net/radio/a_binhameed',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109076',
      name: 'تفسير غريب القرآن',
      englishName: 'تفسير غريب القرآن',
      url: 'https://backup.qurango.net/radio/gareeb-quran',
      category: 'tafsir',
    ),
    QuranRadioItem(
      id: '109077',
      name: 'بدر التركي',
      englishName: 'Bader Alturki',
      url: 'https://backup.qurango.net/radio/bader',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109078',
      name: 'هزاع البلوشي',
      englishName: 'Hazza Al-Balushi',
      url: 'https://backup.qurango.net/radio/hazza',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109082',
      name: 'إذاعة القرآن الكريم - السعودية',
      englishName: 'Holy Quran from Saudia Arabia',
      url: 'https://stream.radiojar.com/0tpy1h0kxtzuv',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109083',
      name: 'الشمائل المحمدية',
      englishName: 'الشمائل المحمدية',
      url: 'https://backup.qurango.net/radio/shmaeel',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109084',
      name: 'نورين محمد صديق',
      englishName: 'Noreen Mohammed Siddiq',
      url: 'https://backup.qurango.net/radio/nourin_siddig',
      category: 'quran',
    ),
  ];
}
