class QuranRadioItem {
  final String id;
  final String name;
  final String englishName;
  final String url;
  final String category;
  final bool isFeatured;

  const QuranRadioItem({
    required this.id,
    required this.name,
    required this.englishName,
    required this.url,
    required this.category,
    this.isFeatured = false,
  });
}

class QuranRadioService {
  static const List<QuranRadioItem> stations = [
    QuranRadioItem(
      id: 'salma_khushoo',
      name: 'تلاوات خاشعة ومختارة',
      englishName: 'Reverent Recitations',
      url: 'https://backup.qurango.net/radio/salma',
      category: 'quran',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'albaqarah_radio',
      name: 'سورة البقرة - متواصلة',
      englishName: 'Surah Al-Baqarah 24/7',
      url: 'https://backup.qurango.net/radio/albaqarah',
      category: 'quran',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'mishary_alafasi',
      name: 'مشاري العفاسي',
      englishName: 'Mishary Alafasi',
      url: 'https://backup.qurango.net/radio/mishary_alafasi',
      category: 'quran',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'abdulbasit_abdulsamad',
      name: 'عبدالباسط عبدالصمد',
      englishName: 'Abdulbasit Abdulsamad',
      url: 'https://backup.qurango.net/radio/abdulbasit_abdulsamad',
      category: 'quran',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'maher_muaiqly',
      name: 'ماهر المعيقلي',
      englishName: 'Maher Al-Muaiqly',
      url: 'https://backup.qurango.net/radio/maher',
      category: 'quran',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'saad_alghamdi',
      name: 'سعد الغامدي',
      englishName: 'Saad Al-Ghamdi',
      url: 'https://backup.qurango.net/radio/saad_alghamdi',
      category: 'quran',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'yasser_aldosari',
      name: 'ياسر الدوسري',
      englishName: 'Yasser Al-Dosari',
      url: 'https://backup.qurango.net/radio/yasser_aldosari',
      category: 'quran',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'alminshawi',
      name: 'محمد صديق المنشاوي',
      englishName: 'Mohammed Siddiq Al-Minshawi',
      url: 'https://backup.qurango.net/radio/mohammed_siddiq_alminshawi',
      category: 'quran',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'alanbiya_radio',
      name: 'قصص الأنبياء',
      englishName: 'Stories of the Prophets',
      url: 'https://backup.qurango.net/radio/alanbiya',
      category: 'varied',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'seerah_radio',
      name: 'في ظلال السيرة النبوية (400 حلقة)',
      englishName: 'In the Shade of Prophetic Seerah',
      url: 'https://backup.qurango.net/radio/fi_zilal_alsiyra',
      category: 'varied',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'sakeenah_radio',
      name: 'آيات السكينة والطمأنينة',
      englishName: 'Verses of Tranquility',
      url: 'https://backup.qurango.net/radio/sakeenah',
      category: 'quran',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'athkar_sabah_radio',
      name: 'أذكار الصباح والمساء',
      englishName: 'Morning & Evening Adhkar',
      url: 'https://backup.qurango.net/radio/athkar_sabah',
      category: 'adhkar',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'tafseer_radio',
      name: 'تفسير القرآن الكريم',
      englishName: 'Holy Quran Tafsir',
      url: 'https://backup.qurango.net/radio/tafseer',
      category: 'tafsir',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'eid_takbeerat',
      name: 'تكبيرات العيد',
      englishName: 'Takbeerat Al-Eid',
      url: 'https://backup.qurango.net/radio/eid',
      category: 'adhkar',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'riyad_radio',
      name: 'رياض الصالحين',
      englishName: 'Riyad As-Salihin',
      url: 'https://backup.qurango.net/radio/riyad',
      category: 'varied',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: 'bokharee_radio',
      name: 'صحيح البخاري',
      englishName: 'Sahih Al-Bukhari',
      url: 'https://backup.qurango.net/radio/saheh-bokharee',
      category: 'varied',
      isFeatured: true,
    ),
    QuranRadioItem(
      id: '1',
      name: 'إبراهيم الأخضر',
      englishName: 'Ibrahim Alakdar',
      url: 'https://backup.qurango.net/radio/ibrahim_alakdar',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '2',
      name: 'شيخ أبو بكر الشاطري',
      englishName: 'Shaik Abu Bakr Al Shatri',
      url: 'https://backup.qurango.net/radio/shaik_abu_bakr_al_shatri',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '3',
      name: 'أحمد العجمي',
      englishName: 'Ahmad Al-Ajmy',
      url: 'https://backup.qurango.net/radio/ahmad_alajmy',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '4',
      name: 'أحمد الحواشي',
      englishName: 'Ahmad Alhawashi',
      url: 'https://backup.qurango.net/radio/ahmad_alhawashi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '5',
      name: 'أحمد صابر',
      englishName: 'Ahmad Saber',
      url: 'https://backup.qurango.net/radio/ahmad_saber',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '6',
      name: 'أحمد نعينع',
      englishName: 'Ahmad Nauina',
      url: 'https://backup.qurango.net/radio/ahmad_nauina',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '7',
      name: 'أكرم العلاقمي',
      englishName: 'Akram Alalaqmi',
      url: 'https://backup.qurango.net/radio/akram_alalaqmi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '8',
      name: 'إدريس أبكر',
      englishName: 'Idrees Abkr',
      url: 'https://backup.qurango.net/radio/idrees_abkr',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '9',
      name: 'الزين محمد أحمد',
      englishName: 'Alzain Mohammad Ahmad',
      url: 'https://backup.qurango.net/radio/alzain_mohammad_ahmad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '10',
      name: 'القارئ ياسين',
      englishName: 'Alqaria Yassen',
      url: 'https://backup.qurango.net/radio/alqaria_yassen',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '11',
      name: 'العيون الكوشي',
      englishName: 'Aloyoon Alkoshi',
      url: 'https://backup.qurango.net/radio/aloyoon_alkoshi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '12',
      name: 'توفيق الصايغ',
      englishName: 'Tawfeeq Assayegh',
      url: 'https://backup.qurango.net/radio/tawfeeq_assayegh',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '13',
      name: 'جمال شاكر عبدالله',
      englishName: 'Jamal Shaker Abdullah',
      url: 'https://backup.qurango.net/radio/jamal_shaker_abdullah',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '14',
      name: 'خالد القحطاني',
      englishName: 'Khaled Alqahtani',
      url: 'https://backup.qurango.net/radio/khaled_alqahtani',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '15',
      name: 'خالد عبدالكافي',
      englishName: 'Khalid Abdulkafi',
      url: 'https://backup.qurango.net/radio/khalid_abdulkafi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '16',
      name: 'خليفة الطنيجي',
      englishName: 'Khalifa Altunaiji',
      url: 'https://backup.qurango.net/radio/khalifa_altunaiji',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '18',
      name: 'سعود الشريم',
      englishName: 'Saud Al-Shuraim',
      url: 'https://backup.qurango.net/radio/saud_alshuraim',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '19',
      name: 'سهل ياسين',
      englishName: 'Sahl Yassin',
      url: 'https://backup.qurango.net/radio/sahl_yassin',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '20',
      name: 'زكي داغستاني',
      englishName: 'Zaki Daghistani',
      url: 'https://backup.qurango.net/radio/zaki_daghistani',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '21',
      name: 'سيد رمضان',
      englishName: 'Sayeed Ramadan',
      url: 'https://backup.qurango.net/radio/sayeed_ramadan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '22',
      name: 'شيرزاد عبدالرحمن طاهر',
      englishName: 'Shirazad Taher',
      url: 'https://backup.qurango.net/radio/shirazad_taher',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '23',
      name: 'صابر عبدالحكم',
      englishName: 'Saber Abdulhakm',
      url: 'https://backup.qurango.net/radio/saber_abdulhakm',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '24',
      name: 'صلاح البدير',
      englishName: 'Salah Albudair',
      url: 'https://backup.qurango.net/radio/salah_albudair',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '25',
      name: 'صلاح الهاشم',
      englishName: 'Salah Alhashim',
      url: 'https://backup.qurango.net/radio/salah_alhashim',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '26',
      name: 'صلاح بو خاطر',
      englishName: 'Slaah Bukhatir',
      url: 'https://backup.qurango.net/radio/slaah_bukhatir',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '27',
      name: 'عادل ريان',
      englishName: 'Adel Ryyan',
      url: 'https://backup.qurango.net/radio/adel_ryyan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '28',
      name: 'عبدالبارئ الثبيتي',
      englishName: 'Abdelbari Altoubayti',
      url: 'https://backup.qurango.net/radio/abdelbari_altoubayti',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '29',
      name: 'عبدالبارئ محمد',
      englishName: 'Abdulbari Mohammad',
      url: 'https://backup.qurango.net/radio/abdulbari_mohammad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '30',
      name: 'عبدالباسط عبدالصمد',
      englishName: 'Abdulbasit Abdulsamad',
      url: 'https://backup.qurango.net/radio/abdulbasit_abdulsamad_mojawwad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '31',
      name: 'عبدالباسط عبدالصمد',
      englishName: 'Abdulbasit Abdulsamad',
      url: 'https://backup.qurango.net/radio/abdulbasit_abdulsamad_warsh',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '33',
      name: 'عبدالرحمن السديس',
      englishName: 'Abdulrahman Al-Sudais',
      url: 'https://backup.qurango.net/radio/abdulrahman_alsudaes',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '34',
      name: 'عبدالعزيز الأحمد',
      englishName: 'Abdul Aziz Alahmad',
      url: 'https://backup.qurango.net/radio/abdul_aziz_alahmad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '35',
      name: 'عبدالله المطرود',
      englishName: 'Abdullah Almattrod',
      url: 'https://backup.qurango.net/radio/abdullah_almattrod',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '36',
      name: 'عبدالله بصفر',
      englishName: 'Abdullah Basfer',
      url: 'https://backup.qurango.net/radio/abdullah_basfer',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '37',
      name: 'عبدالله خياط',
      englishName: 'Abdullah Khayyat',
      url: 'https://backup.qurango.net/radio/abdullah_khayyat',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '38',
      name: 'عبدالله عواد الجهني',
      englishName: 'Abdullah Aljohany',
      url: 'https://backup.qurango.net/radio/abdullah_aljohany',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '39',
      name: 'عبدالرشيد صوفي',
      englishName: 'Abdulrasheed Soufi Khalaf',
      url: 'https://backup.qurango.net/radio/abdulrasheed_soufi_khalaf',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '40',
      name: 'عبدالرشيد صوفي',
      englishName: 'Abdulrasheed Soufi Assosi',
      url: 'https://backup.qurango.net/radio/abdulrasheed_soufi_assosi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '41',
      name: 'عبدالمحسن الحارثي',
      englishName: 'Abdulmohsin Alharthy',
      url: 'https://backup.qurango.net/radio/abdulmohsin_alharthy',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '42',
      name: 'عبدالمحسن القاسم',
      englishName: 'Abdulmohsen Alqasim',
      url: 'https://backup.qurango.net/radio/abdulmohsen_alqasim',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '43',
      name: 'عبدالمحسن العبيكان',
      englishName: 'Abdulmohsin Alobaikan',
      url: 'https://backup.qurango.net/radio/abdulmohsin_alobaikan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '44',
      name: 'عبدالهادي أحمد كناكري',
      englishName: 'Abdulhadi Kanakeri',
      url: 'https://backup.qurango.net/radio/abdulhadi_kanakeri',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '45',
      name: 'عبدالودود حنيف',
      englishName: 'Abdulwadood Haneef',
      url: 'https://backup.qurango.net/radio/abdulwadood_haneef',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '46',
      name: 'علي بن عبدالرحمن الحذيفي',
      englishName: 'Ali Alhuthaifi',
      url: 'https://backup.qurango.net/radio/ali_alhuthaifi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '47',
      name: 'علي الحذيفي',
      englishName: 'Ali Alhuthaifi Qalon',
      url: 'https://backup.qurango.net/radio/ali_alhuthaifi_qalon',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '48',
      name: 'علي جابر',
      englishName: 'Ali Jaber',
      url: 'https://backup.qurango.net/radio/ali_jaber',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '49',
      name: 'علي حجاج السويسي',
      englishName: 'Ali Hajjaj Alsouasi',
      url: 'https://backup.qurango.net/radio/ali_hajjaj_alsouasi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '50',
      name: 'عماد زهير حافظ',
      englishName: 'Emad Hafez',
      url: 'https://backup.qurango.net/radio/emad_hafez',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '51',
      name: 'عمر القزابري',
      englishName: 'Omar Alqazabri',
      url: 'https://backup.qurango.net/radio/omar_alqazabri',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '52',
      name: 'فارس عباد',
      englishName: 'Fares Abbad',
      url: 'https://backup.qurango.net/radio/fares_abbad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '53',
      name: 'ناصر القطامي',
      englishName: 'Nasser Al-Qatami',
      url: 'https://backup.qurango.net/radio/nasser_alqatami',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '54',
      name: 'نبيل الرفاعي',
      englishName: 'Nabil Al Rifay',
      url: 'https://backup.qurango.net/radio/nabil_al_rifay',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '55',
      name: 'نعمة الحسان',
      englishName: 'Neamah Alhassan',
      url: 'https://backup.qurango.net/radio/neamah_alhassan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '56',
      name: 'هاني الرفاعي',
      englishName: 'Hani Arrifai',
      url: 'https://backup.qurango.net/radio/hani_arrifai',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '57',
      name: 'وليد النائحي',
      englishName: 'Waleed Alnaehi',
      url: 'https://backup.qurango.net/radio/waleed_alnaehi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '59',
      name: 'ياسر القرشي',
      englishName: 'Yasser Alqurashi',
      url: 'https://backup.qurango.net/radio/yasser_alqurashi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '60',
      name: 'ياسر المزروعي',
      englishName: 'Yasser Almazroyee',
      url: 'https://backup.qurango.net/radio/yasser_almazroyee',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '61',
      name: 'يحيى حوا',
      englishName: 'Yahya Hawwa',
      url: 'https://backup.qurango.net/radio/yahya_hawwa',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '62',
      name: 'يوسف الشويعي',
      englishName: 'Yousef Alshoaey',
      url: 'https://backup.qurango.net/radio/yousef_alshoaey',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '64',
      name: 'محمد الطبلاوي',
      englishName: 'Mohammad Altablaway',
      url: 'https://backup.qurango.net/radio/mohammad_altablaway',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '65',
      name: 'محمد اللحيدان',
      englishName: 'Mohammed Allohaidan',
      url: 'https://backup.qurango.net/radio/mohammed_allohaidan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '66',
      name: 'محمد أيوب',
      englishName: 'Mohammed Ayyub',
      url: 'https://backup.qurango.net/radio/mohammed_ayyub',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '67',
      name: 'محمد صالح عالم شاه',
      englishName: 'Mohammad Saleh Alim Shah',
      url: 'https://backup.qurango.net/radio/mohammad_saleh_alim_shah',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '68',
      name: 'محمد جبريل',
      englishName: 'Mohammed Jibreel',
      url: 'https://backup.qurango.net/radio/mohammed_jibreel',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '70',
      name: 'محمد صديق المنشاوي',
      englishName: 'Mohammed Siddiq Al-Minshawi',
      url: 'https://backup.qurango.net/radio/mohammed_siddiq_alminshawi_mojawwad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '71',
      name: 'محمد عبدالكريم',
      englishName: 'Mohammad Abdullkarem',
      url: 'https://backup.qurango.net/radio/mohammad_abdullkarem',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '72',
      name: 'محمد عبدالحكيم سعيد العبدالله',
      englishName: 'Mohammad Alabdullah Albizi',
      url: 'https://backup.qurango.net/radio/mohammad_alabdullah_albizi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '73',
      name: 'محمد عبدالحكيم سعيد العبدالله',
      englishName: 'Mohammad Alabdullah Aldorai',
      url: 'https://backup.qurango.net/radio/mohammad_alabdullah_aldorai',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '74',
      name: 'محمود خليل الحصري',
      englishName: 'Mahmoud Khalil Al-Hussary',
      url: 'https://backup.qurango.net/radio/mahmoud_khalil_alhussary',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '75',
      name: 'محمود خليل الحصري',
      englishName: 'Mahmoud Khalil Al-Hussary',
      url: 'https://backup.qurango.net/radio/mahmoud_khalil_alhussary_mojawwad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '76',
      name: 'محمود خليل الحصري',
      englishName: 'Mahmoud Khalil Al-Hussary',
      url: 'https://backup.qurango.net/radio/mahmoud_khalil_alhussary_warsh',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '77',
      name: 'محمود علي البنا',
      englishName: 'Mahmoud Ali  Albanna',
      url: 'https://backup.qurango.net/radio/mahmoud_ali__albanna',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '78',
      name: 'محمود علي البنا',
      englishName: 'Mahmoud Ali  Albanna Mojawwad',
      url: 'https://backup.qurango.net/radio/mahmoud_ali__albanna_mojawwad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '80',
      name: 'مصطفى إسماعيل',
      englishName: 'Mustafa Ismail',
      url: 'https://backup.qurango.net/radio/mustafa_ismail',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '81',
      name: 'مصطفى اللاهوني',
      englishName: 'Mustafa Allahoni',
      url: 'https://backup.qurango.net/radio/mustafa_allahoni',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '82',
      name: 'مصطفى رعد العزاوي',
      englishName: 'Mustafa Raad Alazawy',
      url: 'https://backup.qurango.net/radio/mustafa_raad_alazawy',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '83',
      name: 'مفتاح السلطني',
      englishName: 'Muftah Alsaltany Aldori An Abi Amr',
      url: 'https://backup.qurango.net/radio/muftah_alsaltany_aldori_an_abi_amr',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '84',
      name: 'ماهر شخاشيرو',
      englishName: 'Maher Shakhashero',
      url: 'https://backup.qurango.net/radio/maher_shakhashero',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '85',
      name: 'محمود الشيمي',
      englishName: 'Mahmood Alsheimy',
      url: 'https://backup.qurango.net/radio/mahmood_alsheimy',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '86',
      name: 'خالد المهنا',
      englishName: 'Khalid Almohana',
      url: 'https://backup.qurango.net/radio/khalid_almohana',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '87',
      name: 'عادل الكلباني',
      englishName: 'Adel Alkhalbany',
      url: 'https://backup.qurango.net/radio/adel_alkhalbany',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '88',
      name: 'موسى بلال',
      englishName: 'Mousa Bilal',
      url: 'https://backup.qurango.net/radio/mousa_bilal',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '89',
      name: 'حاتم فريد الواعر',
      englishName: 'Hatem Fareed Alwaer',
      url: 'https://backup.qurango.net/radio/hatem_fareed_alwaer',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '90',
      name: 'محمود الرفاعي',
      englishName: 'Mahmood Al Rifai',
      url: 'https://backup.qurango.net/radio/mahmood_al_rifai',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '91',
      name: 'ابراهيم الدوسري',
      englishName: 'Ibrahim Aldosari',
      url: 'https://backup.qurango.net/radio/ibrahim_aldosari',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '92',
      name: 'مفتاح السلطني',
      englishName: 'Muftah Alsaltany Aldorai',
      url: 'https://backup.qurango.net/radio/muftah_alsaltany_aldorai',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '93',
      name: 'جمعان العصيمي',
      englishName: 'Jamaan Alosaimi',
      url: 'https://backup.qurango.net/radio/jamaan_alosaimi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '94',
      name: 'مفتاح السلطني',
      englishName: 'Muftah Alsaltany',
      url: 'https://backup.qurango.net/radio/muftah_alsaltany',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '95',
      name: 'يوسف بن نوح أحمد',
      englishName: 'Yousef Bin Noah Ahmad',
      url: 'https://backup.qurango.net/radio/yousef_bin_noah_ahmad',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '96',
      name: 'مفتاح السلطني',
      englishName: 'Muftah Alsaltany Ibn Thakwan An Ibn Amr',
      url: 'https://backup.qurango.net/radio/muftah_alsaltany_ibn_thakwan_an_ibn_amr',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '97',
      name: 'معيض الحارثي',
      englishName: 'Moeedh Alharthi',
      url: 'https://backup.qurango.net/radio/moeedh_alharthi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '98',
      name: 'محمد رشاد الشريف',
      englishName: 'Mohammad Rashad Alshareef',
      url: 'https://backup.qurango.net/radio/mohammad_rashad_alshareef',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '99',
      name: 'أحمد خضر الطرابلسي',
      englishName: 'Ahmad Khader Altarabulsi',
      url: 'https://backup.qurango.net/radio/ahmad_khader_altarabulsi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '100',
      name: 'أحمد الطرابلسي',
      englishName: 'Ahmed Altrabulsi',
      url: 'https://backup.qurango.net/radio/ahmed_altrabulsi',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '101',
      name: 'عبدالله الكندري',
      englishName: 'Abdullah Alkandari',
      url: 'https://backup.qurango.net/radio/abdullah_alkandari',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '102',
      name: 'أحمد عامر',
      englishName: 'Ahmed Amer',
      url: 'https://backup.qurango.net/radio/ahmed_amer',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '103',
      name: 'محمد عثمان خان',
      englishName: 'Mohammed Osman Khan',
      url: 'https://backup.qurango.net/radio/mohammed_osman_khan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '104',
      name: 'الدوكالي محمد العالم',
      englishName: 'Addokali Mohammad Alalim',
      url: 'https://backup.qurango.net/radio/addokali_mohammad_alalim',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '105',
      name: 'محمد عبدالكريم',
      englishName: 'Mohammad Abdullkarem Alasbahani',
      url: 'https://backup.qurango.net/radio/mohammad_abdullkarem_alasbahani',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '106',
      name: 'الفاتح محمد الزبير',
      englishName: 'Alfateh Alzubair',
      url: 'https://backup.qurango.net/radio/alfateh_alzubair',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '107',
      name: 'طارق عبدالغني دعوب',
      englishName: 'Tareq Abdulgani Daawob',
      url: 'https://backup.qurango.net/radio/tareq_abdulgani_daawob',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '108',
      name: 'العامة - اذاعة متنوعة لمختلف القراء',
      englishName: 'General Recitations Stream',
      url: 'https://backup.qurango.net/radio/mix',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '111',
      name: 'عبدالرحمن الماجد',
      englishName: 'Abdulrahman Almajed',
      url: 'https://backup.qurango.net/radio/abdulrahman_almajed',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '113',
      name: 'الفتاوى العامة',
      englishName: 'Islamic Fatawa',
      url: 'https://backup.qurango.net/radio/fatwa',
      category: 'tafsir',
    ),
    QuranRadioItem(
      id: '114',
      name: 'الرقية الشرعية',
      englishName: 'Live Ruqyah Shariyyah',
      url: 'https://backup.qurango.net/radio/roqiah',
      category: 'ruqyah',
    ),
    QuranRadioItem(
      id: '117',
      name: 'خالد الجليل',
      englishName: 'Khalid Aljileel',
      url: 'https://backup.qurango.net/radio/khalid_aljileel',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '118',
      name: 'ناصر الماجد',
      englishName: 'Nasser Almajed',
      url: 'https://backup.qurango.net/radio/nasser_almajed',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '119',
      name: 'هيثم الجدعاني',
      englishName: 'Hitham Aljadani',
      url: 'https://backup.qurango.net/radio/hitham_aljadani',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '120',
      name: 'أحمد خليل شاهين',
      englishName: 'Ahmad Shaheen',
      url: 'https://backup.qurango.net/radio/ahmad_shaheen',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '121',
      name: 'عبدالله الموسى',
      englishName: 'Abdullah Almousa',
      url: 'https://backup.qurango.net/radio/abdullah_almousa',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '122',
      name: 'عبدالله الخلف',
      englishName: 'Abdullah Alkhalaf',
      url: 'https://backup.qurango.net/radio/abdullah_alkhalaf',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '123',
      name: 'تراتيل قصيرة متميزة',
      englishName: 'Rare & Short Recitations',
      url: 'https://backup.qurango.net/radio/tarateel',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '139',
      name: 'ماجد الزامل',
      englishName: 'Majed Alzamel',
      url: 'https://backup.qurango.net/radio/majed_alzamel',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '217',
      name: 'بندر بليلة',
      englishName: 'Bandar Balilah',
      url: 'https://backup.qurango.net/radio/bandar_balilah',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '248',
      name: 'ناصر العصفور',
      englishName: 'Nasser Alosfor',
      url: 'https://backup.qurango.net/radio/nasser_alosfor',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '261',
      name: 'محمد أيوب - قراءة مميزة',
      englishName: 'Ayyoub2',
      url: 'https://backup.qurango.net/radio/ayyoub2',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '265',
      name: 'أحمد ديبان',
      englishName: 'Ahmad Deban',
      url: 'https://backup.qurango.net/radio/ahmad_deban',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '274',
      name: 'محمد أبوسنينة',
      englishName: 'Sneineh',
      url: 'https://backup.qurango.net/radio/sneineh',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '275',
      name: 'محمد الأمين قنيوة',
      englishName: 'Qeniwa',
      url: 'https://backup.qurango.net/radio/qeniwa',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '287',
      name: 'عبدالرحمن الشحات',
      englishName: 'A Alshahhat',
      url: 'https://backup.qurango.net/radio/a_alshahhat',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '307',
      name: 'عبدالعزيز سحيم',
      englishName: 'Abdulaziz Suhaim',
      url: 'https://backup.qurango.net/radio/a_sheim',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '10903',
      name: 'صور من حياة الصحابة والتابعين رضوان الله عليهم',
      englishName: 'Sahabah',
      url: 'https://backup.qurango.net/radio/sahabah',
      category: 'varied',
    ),
    QuranRadioItem(
      id: '10904',
      name: 'المختصر في تفسير القرآن الكريم',
      englishName: 'Holy Quran Tafsir',
      url: 'https://backup.qurango.net/radio/mukhtasartafsir',
      category: 'tafsir',
    ),
    QuranRadioItem(
      id: '10907',
      name: 'أذكار المساء',
      englishName: 'Evening Adhkar',
      url: 'https://backup.qurango.net/radio/athkar_masa',
      category: 'adhkar',
    ),
    QuranRadioItem(
      id: '21115',
      name: 'المختصر في السيرة النبوية',
      englishName: 'In the Shade of Prophetic Seerah',
      url: 'https://backup.qurango.net/radio/almukhtasar_fi_alsiyra',
      category: 'varied',
    ),
    QuranRadioItem(
      id: '21116',
      name: 'كتاب الاختيارات الفقهية في مسائل العبادات والمعاملات',
      englishName: 'Alaikhtiarat Alfiqhayh Bin Baz',
      url: 'https://backup.qurango.net/radio/alaikhtiarat_alfiqhayh_bin_baz',
      category: 'tafsir',
    ),
    QuranRadioItem(
      id: '21117',
      name: 'تفسير القران الكريم-الخلاصة من تفسير الطبري',
      englishName: 'Tabri',
      url: 'https://backup.qurango.net/radio/tabri',
      category: 'tafsir',
    ),
    QuranRadioItem(
      id: '109038',
      name: 'صالح الهبدان',
      englishName: 'Saleh Alhabdan',
      url: 'https://backup.qurango.net/radio/saleh_alhabdan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109039',
      name: 'ترجمة معاني القرآن باللغة الأوردية - عبدالباسط عبدالصمد',
      englishName: 'Abdulbasit Abdulsamad',
      url: 'https://backup.qurango.net/radio/translation_quran_urdu_basit',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109040',
      name: 'ترجمة معاني القرآن باللغة الأسبانية',
      englishName: 'Translation Spanish Afs',
      url: 'https://backup.qurango.net/radio/translation_quran_spanish_afs',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109041',
      name: 'ترجمة معاني القرآن باللغة الألبانية',
      englishName: 'Translation Albanian',
      url: 'https://backup.qurango.net/radio/translation_quran_albanian',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109042',
      name: 'ترجمة معاني القرآن باللغة الألمانية',
      englishName: 'Translation German',
      url: 'https://backup.qurango.net/radio/translation_quran_german',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109043',
      name: 'ترجمة معاني القرآن باللغة الأمازيغية',
      englishName: 'Translation Tamazight',
      url: 'https://backup.qurango.net/radio/translation_quran_tamazight',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109044',
      name: 'ترجمة معاني القرآن باللغة الأوردية',
      englishName: 'Translation Urdu Sds Shur',
      url: 'https://backup.qurango.net/radio/translation_quran_urdu_sds_shur',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109045',
      name: 'ترجمة معاني القرآن باللغة الأوردية',
      englishName: 'Translation Urdu Minsh',
      url: 'https://backup.qurango.net/radio/translation_quran_urdu_minsh',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109046',
      name: 'ترجمة معاني القرآن باللغة الإنجليزية',
      englishName: 'Translation English Basit',
      url: 'https://backup.qurango.net/radio/translation_quran_english_basit',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109047',
      name: 'ترجمة معاني القرآن باللغة الإنجليزية',
      englishName: 'Translation English Bsfr',
      url: 'https://backup.qurango.net/radio/translation_quran_english_bsfr',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109048',
      name: 'ترجمة معاني القرآن باللغة الإنجليزية -ترجمة والك',
      englishName: 'Translation English Walk Basit',
      url: 'https://backup.qurango.net/radio/translation_quran_english_walk_basit',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109049',
      name: 'ترجمة معاني القرآن باللغة البرتغالية',
      englishName: 'Translation Portuguese',
      url: 'https://backup.qurango.net/radio/translation_quran_portuguese',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109050',
      name: 'ترجمة معاني القرآن باللغة البوسنية',
      englishName: 'Translation Bosnia',
      url: 'https://backup.qurango.net/radio/translation_quran_bosnia',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109051',
      name: 'ترجمة معاني القرآن باللغة التركية',
      englishName: 'Translation Turkish',
      url: 'https://backup.qurango.net/radio/translation_quran_turkish',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109052',
      name: 'ترجمة معاني القرآن باللغة الروسية',
      englishName: 'Translation Russia',
      url: 'https://backup.qurango.net/radio/translation_quran_Russia',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109053',
      name: 'ترجمة معاني القرآن باللغة الصينية',
      englishName: 'Translation Chinese',
      url: 'https://backup.qurango.net/radio/translation_quran_chinese',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109054',
      name: 'ترجمة معاني القرآن باللغة الفارسية',
      englishName: 'Translation Farsi',
      url: 'https://backup.qurango.net/radio/translation_quran_farsi',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109055',
      name: 'ترجمة معاني القرآن باللغة الفرنسية',
      englishName: 'Translation French',
      url: 'https://backup.qurango.net/radio/translation_quran_french',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109056',
      name: 'ترجمة معاني القرآن باللغة الكردية',
      englishName: 'Translation Kurdish',
      url: 'https://backup.qurango.net/radio/translation_quran_kurdish',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109057',
      name: 'ترجمة معاني القرآن باللغة الكورية',
      englishName: 'Translation Korean',
      url: 'https://backup.qurango.net/radio/translation_quran_Korean',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109058',
      name: 'ترجمة معاني القرآن باللغة المجرية',
      englishName: 'Translation Hungarian',
      url: 'https://backup.qurango.net/radio/translation_quran_hungarian',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109059',
      name: 'ترجمة معاني القرآن باللغة اليونانية',
      englishName: 'Translation Greek',
      url: 'https://backup.qurango.net/radio/translation_quran_greek',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109060',
      name: 'سورة الملك',
      englishName: 'Surah Al-Mulk',
      url: 'https://backup.qurango.net/radio/Surah_Al-Mulk',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109061',
      name: 'فضل شهر رمضان',
      englishName: 'Ramadan',
      url: 'https://backup.qurango.net/radio/ramadan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109062',
      name: 'ترجمة معاني القرآن باللغة الهوسا',
      englishName: 'Translation Hausa',
      url: 'https://backup.qurango.net/radio/Translation_Quran_Hausa',
      category: 'translations',
    ),
    QuranRadioItem(
      id: '109066',
      name: 'صحيح مسلم',
      englishName: 'Sahih Muslim',
      url: 'https://backup.qurango.net/radio/saheh-muslim',
      category: 'varied',
    ),
    QuranRadioItem(
      id: '109074',
      name: 'عبدالله البعيجان',
      englishName: 'Buajan',
      url: 'https://backup.qurango.net/radio/buajan',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109075',
      name: 'أحمد طالب بن حميد',
      englishName: 'A Binhameed',
      url: 'https://backup.qurango.net/radio/a_binhameed',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109076',
      name: 'تفسير غريب القرآن',
      englishName: 'Gareeb Quran',
      url: 'https://backup.qurango.net/radio/gareeb-quran',
      category: 'tafsir',
    ),
    QuranRadioItem(
      id: '109077',
      name: 'بدر التركي',
      englishName: 'Bader',
      url: 'https://backup.qurango.net/radio/bader',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109078',
      name: 'هزاع البلوشي',
      englishName: 'Hazza Al-Balushi',
      url: 'https://backup.qurango.net/radio/hazza',
      category: 'quran',
    ),
    QuranRadioItem(
      id: '109083',
      name: 'الشمائل المحمدية',
      englishName: 'Ash-Shama\'il Al-Muhammadiyyah',
      url: 'https://backup.qurango.net/radio/shmaeel',
      category: 'varied',
    ),
    QuranRadioItem(
      id: '109084',
      name: 'نورين محمد صديق',
      englishName: 'Noreen Mohammed Siddiq',
      url: 'https://backup.qurango.net/radio/nourin_siddig',
      category: 'quran',
    ),
  ];
}
